project:
  type: website
  output-dir: docs
  resources:
    - google4818da035978b4e5.html

website:
  title: "Kseniya Bortnikova"
  
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



